### ISSUE TITLE
rJava dependencies loading script

### ISSUE THREAD

**Issue by maytag42** [elias-jhsph/rocker-flask#1]
https://askubuntu.com/questions/1168264/problem-installing-rjava-with-r-3-6-on-ubuntu-18-04

sudo apt-get install -y default-jre
sudo apt-get install -y default-jdk
sudo R CMD javareconf

**Comment by eliaswestonfarber** [comment]
This shouldn't be necessary but if you are setting up R outside of docker in bare Ubuntu this may help
